services:
  vsserver:
    image: ${IMAGE:-ghcr.io/zcmace/vintage-story-server}:${VS_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VS_VERSION=${VS_VERSION:-1.22.1}
    container_name: vintagestory_server
    ports:
      - "42420:42420"
      - "42420:42420/udp"
    volumes:
      - ${VS_DATA_PATH:-./vintage_story/data}:/var/vintagestory/data
    environment:
      - VS_VERSION=${VS_VERSION:-1.22.1}
    networks:
      - vintagestory_network
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: vs_filebrowser
    ports:
      - "8080:8080"
    volumes:
      - ${VS_DATA_PATH:-./vintage_story/data}:/srv
      - filebrowser_db:/database
    networks:
      - vintagestory_network
    restart: unless-stopped

volumes:
  filebrowser_db:

networks:
  vintagestory_network:
    driver: bridge
